# This template is used in local demo.

rotation:
    logLimit: 104857600 # 100 MB
    keepFiles: 20
printOutput: False
termSeveritiesOut: []
termSeveritiesErr: []
loggerTree:
  severity: Debug+
  files:
    - node.pub
    - node
