resolver: lts-9.1

flags:
  ether:
    disable-tup-instances: true

packages:
- ./ariadne
- ./ui/qt
- ./ui/vty
- ./knit
- ./util/

- location:
    git: ssh://git@github.com/serokell/lootbox.git
    commit: 983b19bd438a47c91184b0b71213e76cc9983b03 # gromak/workaround-stack2nix branch
  extra-dep: true
  subdirs:
  - code/crypto
  - code/prelude

- location:
    git: https://github.com/serokell/cardano-sl.git
    commit: bb1ab1fd93acee9986e91d45121dbcf471bbca5b # ariadne branch
  extra-dep: true
  subdirs:
  - binary
  - block
  - client
  - core
  - crypto
  - db
  - delegation
  - generator
  - infra
  - lib
  - lrc
  - networking
  - ssc
  - txp
  - update
  - util
  - wallet

# Cardano SL - please keep in sync
- location:
    git: https://github.com/well-typed/cborg
    # Has support for canonical cbor
    commit: 3d274c14ca3077c3a081ba7ad57c5182da65c8c1
  subdirs:
  - cborg
  extra-dep: true
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 9a8af2440d655e14b802639b0b363be2ffb5a32a
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: d4aa461fc69fc6957aab46b41a670c2144aefb77
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 81eea7361a75923f9402fcb7840fb36722dbf88e # master 0.4.10
  extra-dep: true
# These three are needed for cardano-sl-networking
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true
- location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 287cc575fafe86af9d24af9d012c47f9d3f04da0
  extra-dep: true
# We're using forked version of 'swagger2' package because of bug in haddock package.
# Now we don't build Haddock-docs for this 'swagger2' package, and when that bug will
# be fixed, we'll back to Hackage-version.
- location:
    git: https://github.com/serokell/swagger2
    commit: 6693ff91be2f0b015c2ab043292587c1cc9449cf
  extra-dep: true
# Version of "dns" with proper Windows & Unix multiple-nameservers support
- location:
    git: https://github.com/kazu-yamamoto/dns.git
    commit: b106470f0a93672af22cbc7ed6564b53c0f249ed
  extra-dep: true
- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: 2d261bb971bada1893753b503452d9e6e217bc4a
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true
# I don't think making a PR to servant is a good idea at this point
- location:
    git: https://github.com/serokell/servant.git
    commit: 5db013cc36894afdff9e748dbc1c05947c54df3d
  extra-dep: true
  subdirs:
    - servant-server
- location:
    git: https://github.com/serokell/servant-multipart.git
    commit: e7de56b5f7c39f8dc473f1bbaf534bb7affc3cf4
  extra-dep: true
- location:
    git: https://github.com/serokell/log-warper.git
    commit: 7f95c6990ef93a289678755cb1db71c2a4ecdfb5
  extra-dep: true

# Not for Cardano SL
- location:
    git: ssh://git@github.com/serokell/qtah.git
    commit: 6bb0cdfb46239a63fdb38ceacc70a23bc38d8335
  extra-dep: true
  subdirs:
  - qtah-generator
  - qtah-cpp
  - qtah


extra-deps:

# Common
- async-2.2.1                     # fixes https://github.com/simonmar/async/issues/59
# Cardano SL
- ekg-core-0.1.1.3                # https://github.com/tibbe/ekg-core/pull/21
- transformers-0.5.5.0            # https://hub.darcs.net/ross/transformers/issue/33#comment-20171004T152940
- universum-0.9.0
- serokell-util-0.5.2
- pvss-0.2.0
- base58-bytestring-0.1.0
- concurrent-extra-0.7.0.10       # not yet on Stackage
- directory-1.3.1.0               # https://github.com/malcolmwallace/cpphs/issues/8
- servant-0.12
- servant-client-0.12
- servant-client-core-0.12
- servant-docs-0.11.1             # needed for servant-0.12
- servant-swagger-1.1.4           # needed for servant-0.12
- servant-swagger-ui-0.2.4.3.4.0  # needed for servant-0.12
- servant-blaze-0.7.1             # needed for servant-0.12
- servant-quickcheck-0.0.4
- ether-0.5.1.0
- pipes-interleave-1.1.1
- generic-arbitrary-0.1.0
- happy-1.19.5                    # https://github.com/commercialhaskell/stack/issues/3151
- entropy-0.3.7                   # https://github.com/commercialhaskell/stack/issues/3151
- fmt-0.5.0.0
- systemd-1.1.2
- tabl-1.0.3
# ekg-statsd version without the unnecessary diffing optimisation
- ekg-statsd-0.2.2.0
# https://github.com/fpco/lts-haskell/issues/70
- fgl-5.5.3.1
- megaparsec-6.2.0
- parser-combinators-0.2.0
- lens-sop-0.2.0.2
- json-sop-0.2.0.3
- servant-generic-0.1.0.1
- cryptonite-openssl-0.7
- basement-0.0.7
# See CSL-2231
- conduit-1.3.0
- conduit-extra-1.3.0
- mono-traversable-1.0.8.1
- resourcet-1.2.0
- yaml-0.8.28
- lzma-0.0.0.3
- lzma-clib-5.2.2
- lzma-conduit-1.2.1 # https://github.com/alphaHeavy/lzma-conduit/pull/18
- wai-extra-3.0.22.0
- typed-process-0.2.1.0
- unliftio-0.2.4.0
- unliftio-core-0.1.1.0
- http-conduit-2.3.0

# Ariadne
- dhall-1.7.0
- loc-0.1.3.2
- config-ini-0.2.2.0
- vty-5.21
- brick-0.36
- word-wrap-0.4.1
- validation-0.6.1
- vinyl-0.8.1.1
- union-0.1.1.2
- named-0.1.0.0

# Ariadne Qt GUI
- hoppy-runtime-0.4.0
- hoppy-generator-0.4.0
- hoppy-std-0.4.0
- haskell-src-1.0.2.0   # https://github.com/commercialhaskell/stack/issues/3151
- html-entities-1.1.4.2

extra-package-dbs: []

nix:
  shell-file: shell.nix
  pure: true

flags:
  qtah:
    qt5: true
  qtah-cpp:
    qt5: true
