resolver: lts-11.13

flags:
  ether:
    disable-tup-instances: true
  qtah:
    qt5: true
  qtah-cpp:
    qt5: true

packages:
- ./ariadne/core
- ./ariadne/cardano
- ./ui/qt-app
- ./ui/qt-lib
- ./ui/vty-app
- ./ui/vty-lib
- ./knit
- ./acid-view

extra-deps:
- git: https://github.com/serokell/cardano-sl
  commit: e5ccf2e2c504569814796c00ab5887f3e05d394a # ariadne branch
  subdirs:
  - binary
  - binary/test
  - block
  - block/test
  - client
  - core
  - core/test
  - crypto
  - crypto/test
  - db
  - delegation
  - delegation/test
  - generator
  - infra
  - lib
  - lrc
  - lrc/test
  - networking
  - ssc
  - txp
  - txp/test
  - update
  - util
  - util/test
  - wallet

# Cardano SL dependencies - please keep in sync
- git: https://github.com/well-typed/cborg
  commit: 3d274c14ca3077c3a081ba7ad57c5182da65c8c1
  subdirs:
  - cborg
- git: https://github.com/serokell/time-units
  commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
- git: https://github.com/serokell/kademlia
  commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master
- git: https://github.com/avieth/plutus-prototype
  commit: d094be301195fcd8ab864d793f114970426a4478
- git: https://github.com/thoughtpolice/hs-ed25519
  # We're waiting on next release
  commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
- git: https://github.com/input-output-hk/cardano-report-server
  commit: 9b96874d0f234554a5779d98762cc0a6773a532a

# These three are needed for cardano-sl-networking
- git: https://github.com/serokell/network-transport-tcp
  commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
- git: https://github.com/serokell/network-transport
  commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
- git: https://github.com/avieth/network-transport-inmemory
  commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
- git: https://github.com/input-output-hk/cardano-crypto
  commit: 33c7ecc6e4bd71c3ea0195e9d796eeace7be22cf
  # to be removed when haskell-ip is in the current stackage version
- git: https://github.com/andrewthad/haskell-ip
  commit: 9bb453139aa82cc973125091800422a523e1eb8f

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- git: https://github.com/input-output-hk/engine.io
  commit: d3c55f51bb81cee7d0d551de930ce65fe7d76756
  subdirs:
  - socket-io
  - engine-io
  - engine-io-wai

- git: https://github.com/well-typed/canonical-json
  commit: 2d261bb971bada1893753b503452d9e6e217bc4a

- git: https://github.com/input-output-hk/rocksdb-haskell-ng
  commit: 49f501a082d745f3b880677220a29cafaa181452

# Because log-warper mainline depends on a lifted-async which depends upon a
# buggy async
- git: https://github.com/input-output-hk/log-warper
  commit: fa925f9dadf239b38e2ffcc35f9d241a9fcb7d55

# Because it includes a bunch of safecopy instances that we currently rely upon.
# Also the 'Serokell.AcidState.ExtendedState' thing.
- git: https://github.com/serokell/acid-state
  commit: bae90f7565b4fc621cd45ac94d211b7b84627465

- git: https://github.com/input-output-hk/haskell-hedgehog
  commit: 2e741bb53afb085741807018948ae17d956c53af
  subdirs:
  - hedgehog

- git: https://github.com/avieth/servant-quickcheck
  commit: e4e879abca99d0d56015765859fb37af59a81dbb

# Ariadne dependencies

## We are using our fork because we added some stuff there
- git: https://github.com/serokell/qtah
  # srk-september branch until merged upstream
  commit: 4c682417290759b377623babdeca3b6259839c1e
  subdirs:
  - qtah-generator
  - qtah-cpp
  - qtah

## Lootbox is not on Hackage
- git: https://github.com/serokell/lootbox
  commit: f287dd6cfe29707b28cc0418e8aa099de3bfbe77 # master
  subdirs:
  - code/crypto
  - code/prelude

# From `cardano-sl`:
# Very important! First release with a fix of 'race' and 'cancel'.
#   https://github.com/simonmar/async/issues/59
#   https://github.com/simonmar/async/issues/81
# It has yet to appear in an LTS.
- async-2.2.1
# There are 2 asyncs -_-
- lifted-async-0.10.0.1
# Stackage has hinotify-0.3.9 which requires async < 2.2
# This older version requires no async.
- hinotify-0.3.8.1
# Required by backend test from cardano-sl-wallet-new
- normaldistribution-1.1.0.3

# Serokell stuff
- universum-1.1.0
- serokell-util-0.8.0
# Because serokell-util
- formatting-6.2.5

# Following 9 are not on stackage.
- pvss-0.2.0
- base58-bytestring-0.1.0
- pipes-interleave-1.1.2
- systemd-1.1.2
- tabl-1.0.3
- loc-0.1.3.2
- lens-sop-0.2.0.2
- json-sop-0.2.0.3
- lzma-clib-5.2.2
# ekg-statsd version without the unnecessary diffing optimisation
- ekg-statsd-0.2.2.0
# https://github.com/fpco/lts-haskell/issues/70
# Also, graphviz latest needs ghl >=5.4 && <5.6, but stackage has 5.6
- fgl-5.5.3.1
# Good bug fixes in here.
- criterion-1.4.0.0
# Gauge _and_ criterion? Ok, whatever.
- gauge-0.2.1
- beam-sqlite-0.3.2.1
- beam-core-0.7.2.1
- beam-migrate-0.3.2.0

# Servant stuff not found on stackage
- servant-multipart-0.11.1
# Because of servant-quickcheck
# It defines serverSatisfiesMgr, but requires a newer hspec.
- hspec-2.5.1
- hspec-core-2.5.1
- hspec-discover-2.5.1

# Graphics stuff not found on stackage.
- Chart-diagrams-1.8.2
- graphviz-2999.19.0.0
- diagrams-core-1.4.0.1
# diagrams-core implies lens < 4.16
- lens-4.15.4
# lens-4.15.4 implies free < 5
- free-4.12.4
- diagrams-lib-1.4.2
- diagrams-postscript-1.4
- diagrams-svg-1.4.1.1
- diagrams-solve-0.1.1
- SVGFonts-1.6.0.3
- dual-tree-0.2.1
- pretty-show-1.6.16

# Support for wallet's Txmeta tracking
- sqlite-simple-errors-0.6.1.0

# Ariadne specific
- cryptonite-openssl-0.7
- vty-5.21
- brick-0.37.1
- vinyl-0.8.1.1
- named-0.2.0.0
- base-noprelude-4.10.1.0 # due to lootbox
- componentm-0.0.0.2
- teardown-0.5.0.0
- unix-compat-0.5.1 # https://github.com/jystic/unix-compat/pull/40
- ntype-0.1.0.0
- dhall-1.15.1

# Required by https://github.com/input-output-hk/cardano-sl/pull/3232
- micro-recursion-schemes-5.0.2.2

## Ariadne Qt GUI specific
- hoppy-runtime-0.5.0
- hoppy-generator-0.5.0
- hoppy-std-0.5.0
- html-entities-1.1.4.1 # https://github.com/nikita-volkov/html-entities/issues/8

nix:
  shell-file: shell-native.nix
