resolver: lts-9.1

packages:
- .

- location:
    git: https://github.com/input-output-hk/cardano-sl.git
    commit: d2d3998b17a63c1b5e8339750789af07eafc3e09
  extra-dep: true
  subdirs:
  - auxx
  - binary
  - block
  - client
  - core
  - crypto
  - db
  - delegation
  - generator
  - infra
  - lib
  - lrc
  - networking
  - ssc
  - txp
  - update
  - util

- location:
    git: https://github.com/serokell/acid-state.git
    commit: 9a8af2440d655e14b802639b0b363be2ffb5a32a
  extra-dep: true

- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: 2d261bb971bada1893753b503452d9e6e217bc4a
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 19fd5ddf24dab731375a156ce38dcfce4319d1e4
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/cardano-crypto.git
    commit: 480839f6ebeec5fd45ffeccc9eeef27df315fae6
  extra-dep: true

- location:
    git: https://github.com/well-typed/cborg
    commit: 8bddf97abe613d4eb523ed6b0ff8eabbd713c744
  extra-dep: true
  subdirs:
  - cborg

- location:
    git: https://github.com/input-output-hk/plutus-prototype.git
    commit: 9f66b6baf444245e5eda37f4e603dc0507d9bb45
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true

- location:
    git: https://github.com/serokell/servant.git
    commit: 5db013cc36894afdff9e748dbc1c05947c54df3d
  extra-dep: true
  subdirs:
    - servant-server

- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f
  extra-dep: true

- location:
    git: https://github.com/serokell/log-warper.git
    commit: 7f95c6990ef93a289678755cb1db71c2a4ecdfb5
  extra-dep: true

extra-deps:
- universum-0.9.0
- serokell-util-0.5.2
- pvss-0.2.0
- base58-bytestring-0.1.0
- concurrent-extra-0.7.0.10
- servant-0.12
- servant-client-0.12
- servant-client-core-0.12
- servant-swagger-1.1.4
- servant-quickcheck-0.0.4
- generic-arbitrary-0.1.0
- fmt-0.5.0.0
- systemd-1.1.2
- ekg-statsd-0.2.2.0
- fgl-5.5.3.1
- loc-0.1.3.1
- conduit-1.3.0
- conduit-extra-1.3.0
- mono-traversable-1.0.8.1
- resourcet-1.2.0
- yaml-0.8.28
- lzma-0.0.0.3
- lzma-clib-5.2.2
- wai-extra-3.0.22.0
- typed-process-0.2.1.0
- unliftio-0.2.4.0
- unliftio-core-0.1.1.0
- http-conduit-2.3.0
- basement-0.0.6
- time-units-1.0.0
- dns-3.0.2

extra-package-dbs: []
