resolver: lts-11.13

flags:
  ether:
    disable-tup-instances: true
  qtah:
    qt5: true
  qtah-cpp:
    qt5: true

packages:
- ./ariadne/core
- ./ariadne/cardano
- ./ui/qt-app
- ./ui/qt-lib
- ./ui/vty-app
- ./ui/vty-lib
- ./knit
- ./acid-view

extra-deps:
- git: https://github.com/serokell/cardano-sl
  commit: 5e1b28ce794fdf8864b23df0425f73214dc09b38 # ariadne branch
  subdirs:
  - binary
  - binary/test
  - chain
  - chain/test
  - client
  - core
  - core/test
  - crypto
  - crypto/test
  - db
  - infra
  - lib
  - networking
  - util
  - util/test

# Cardano SL dependencies - please keep in sync
# Note: we are using our own universum and serokell-util
# IOHK projects:

# TODO(parsonsmatt): There have been some breaking changes with Plutus for
# cardano-sl and it would be nice to have some help from that team to get this
# updated and back on IOHK.
- git: https://github.com/avieth/plutus-prototype
  commit: d094be301195fcd8ab864d793f114970426a4478

- git: https://github.com/serokell/cardano-report-server.git
  commit: a46274e47ec70f540c3c654cc77d7a3d215822c7

- git: https://github.com/input-output-hk/cardano-crypto
  commit: e87fcd3fea18f664d6e4f39c11abb8cafbd25785
# to be removed when haskell-ip is in the current stackage version
- git: https://github.com/andrewthad/haskell-ip
  commit: 9bb453139aa82cc973125091800422a523e1eb8f

## Vendored/Forked dependencies
#
# For these projects, please include a note describing:
# 1. why we're using a fork
# 2. what branch the commit is on
# 3. a link to the PR that upstreams the patch
#
# Has support for canonical cbor. This commit is pulled into `master`. I've
# posted a GitHub issue requesting a Hackage release:
# https://github.com/well-typed/cborg/issues/171
- git: https://github.com/well-typed/cborg
  commit: 3d274c14ca3077c3a081ba7ad57c5182da65c8c1
  subdirs:
  - cborg

# this extra-dep is to avoid printing microseconds with unicode
# no PR upstream was made
# TODO(parsonsmatt): why was this change done?
- git: https://github.com/serokell/time-units.git
  commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132

# not reviewing this too deeply as we're dumping kademlia
- git: https://github.com/serokell/kademlia.git
  commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master

# These three are needed for cardano-sl-networking
#
# This defines a bundle type and attribute:
# https://github.com/haskell-distributed/network-transport/compare/master...serokell:018a50b9042c2115c3ec9c9fd5ca5f28737dd29c?expand=1
# Seems relatively straightforward to PR.
- git: https://github.com/serokell/network-transport
  commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

# This doesn't have much difference at all with the upstream master:
# https://github.com/haskell-distributed/network-transport-tcp/compare/master...serokell:3d56652123bd296dc759cd31947eb2a17924e68a?expand=1
# As above, seems relatively straightforward to PR.
- git: https://github.com/serokell/network-transport-tcp
  commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0

# This one has more changes:
# https://github.com/haskell-distributed/network-transport-inmemory/compare/master...avieth:5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a?expand=1
# Do we have an issue that documents why we made these changes, so we can make a PR upstream?
- git: https://github.com/avieth/network-transport-inmemory
  commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a

# Waiting on the space leak bug fix PR to be merged:
# https://github.com/acid-state/acid-state/pull/104
- git: https://github.com/parsonsmatt/acid-state
  commit: a1b23e2056f134e53f705a694ab85deeecabec5c

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- git: https://github.com/input-output-hk/engine.io.git
  commit: d3c55f51bb81cee7d0d551de930ce65fe7d76756
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

# Library has never been released on Hackage yet
- git: https://github.com/input-output-hk/canonical-json.git
  commit: f66762e4c4fe484ed109d28ad541fc55cc841c2c

# The latest release of clock on hackage is *way* too old (0.7.2)
# and can not be cross compiled.  As
# https://github.com/corsis/clock/commit/f7fe4fb5691d56c342e6fbf5a99c121ab24a6b41
# hasn't made it into any release yet.
- git: https://github.com/corsis/clock.git
  commit: ef60bd51a3587a173adf565c33bf2886df6e3842

# Library has never been released on Hackage yet
- git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
  commit: 49f501a082d745f3b880677220a29cafaa181452

# Exposes a custom discovery function so you can specify the prefix.
# https://github.com/hedgehogqa/haskell-hedgehog/compare/master...input-output-hk:master
- git: https://github.com/input-output-hk/haskell-hedgehog.git
  commit: 2e741bb53afb085741807018948ae17d956c53af
  subdirs:
    - hedgehog

# servant-quickcheck has a doc/doc.cabal file that is poorly specified and this
# breaks the mafia build tool.
- git: https://github.com/avieth/servant-quickcheck.git
  commit: e4e879abca99d0d56015765859fb37af59a81dbb

# Add custom stylish-haskell while waiting for PR upstream: https://github.com/jaspervdj/stylish-haskell/pull/214
- git: https://github.com/input-output-hk/stylish-haskell.git
  commit: ecfd3b307d8d13a6d12aff03055f25a39a17e182


# Ariadne dependencies

## We are using our fork because we added some stuff there
- git: https://github.com/serokell/qtah
  # srk-september branch until merged upstream
  commit: 4c682417290759b377623babdeca3b6259839c1e
  subdirs:
  - qtah-generator
  - qtah-cpp
  - qtah

## Lootbox is not on Hackage
- git: https://github.com/serokell/lootbox
  commit: f287dd6cfe29707b28cc0418e8aa099de3bfbe77 # master
  subdirs:
  - code/crypto
  - code/prelude

# From `cardano-sl`:
# Needed to fix an issue with CTX_INIT failing to build on newer openssl
# versions.
- cryptonite-openssl-0.7
# Very important! First release with a fix of 'race' and 'cancel'.
#   https://github.com/simonmar/async/issues/59
#   https://github.com/simonmar/async/issues/81
# It has yet to appear in an LTS.
- async-2.2.1
# There are 2 asyncs -_-
- lifted-async-0.10.0.1

# Serokell-specific utilities not on stackage
- fmt-0.6.1

# Following 10 are not on stackage.
- pvss-0.2.0
- systemd-1.1.2
- base58-bytestring-0.1.0
- pipes-interleave-1.1.2
- tabl-1.0.3
- loc-0.1.3.2
- json-sop-0.2.0.3
- lens-sop-0.2.0.2
- lzma-clib-5.2.2
- micro-recursion-schemes-5.0.2.2

# The changelog for directory-1.3.1.1 indicate some potentially important
# bugfixes over directory-1.3.0.2, which is what's on lts-11.
- directory-1.3.1.1
# https://github.com/commercialhaskell/stack/issues/3151
- happy-1.19.5
# Good bug fixes in here.
- criterion-1.4.0.0

- katip-0.5.5.1
# Fix for a space leak: https://github.com/chrisdone/formatting/pull/44
- formatting-6.3.6

# Servant stuff not found on stackage
- servant-multipart-0.11.2
# Because of servant-quickcheck
# It defines serverSatisfiesMgr, but requires a newer hspec.
- hspec-2.5.1
- hspec-core-2.5.1
- hspec-discover-2.5.1

# Graphics stuff not found on stackage.
- Chart-diagrams-1.8.3
- graphviz-2999.19.0.0
- diagrams-core-1.4.1.1
- diagrams-lib-1.4.2.2
- diagrams-postscript-1.4.1
- diagrams-svg-1.4.2
- diagrams-solve-0.1.1
- SVGFonts-1.6.0.3
- dual-tree-0.2.1
- fgl-5.5.4.0

# Support for wallet's Txmeta tracking
- sqlite-simple-errors-0.6.1.0

# Working around a stack issue with rebuilding dependencies
- pretty-show-1.7

# Needed for coin selection in the wallet
- normaldistribution-1.1.0.3

# This used to be Serokell.Aeson.Options
- aeson-options-0.0.0

# universum depends on tasty-hedgehog
# tasty-hedgehog < 0.2 depends on hedgehog < 0.6
# LTS-11.13 -- LTS-11.17 provide tasty-hedgehog-0.1.0.2
# thus to use our hedgehog-0.6+ from source,
# we need to explicilty bump tasty-hedgehog to 0.2.0.0.
- tasty-hedgehog-0.2.0.0

- file-embed-lzma-0
- servant-swagger-ui-core-0.3.1
- servant-swagger-ui-0.3.0.3.13.2
- servant-swagger-ui-redoc-0.3.0.1.21.2

- fsnotify-0.2.1.2
- hinotify-0.3.10

# Ariadne specific
- universum-1.2.0 # we are using our own universum
- serokell-util-0.10.0 # we are using our own serokell-util
- o-clock-1.0.0.1 # due to serokell-util
- tiempo-0.0.1.1 # due to o-clock and nix :facepalm:
- vty-5.21
- brick-0.37.1
- vinyl-0.8.1.1
- named-0.2.0.0
- base-noprelude-4.10.1.0 # due to lootbox
- componentm-0.0.0.2
- teardown-0.5.0.0
- unix-compat-0.5.1 # https://github.com/jystic/unix-compat/pull/40
- ntype-0.1.0.0
- contravariant-1.5 # needed for co-log
- typerep-map-0.3.0 # needed for co-log
- dhall-1.15.1      # needed due to contravariant
- co-log-core-0.1.1
- co-log-0.2.0

## Ariadne Qt GUI specific
- hoppy-runtime-0.5.0
- hoppy-generator-0.5.0
- hoppy-std-0.5.0
- html-entities-1.1.4.1 # https://github.com/nikita-volkov/html-entities/issues/8

nix:
  shell-file: shell-native.nix
