module Ariadne.Wallet.Face
  ( module Ariadne.Cardano.Face
  , WalletFace(..)
  , WalletEvent(..)
  ) where

import Ariadne.Cardano.Face

data WalletFace =
  WalletFace
    { walletAddAccount :: CardanoMode ()
    , walletRefreshUserSecret :: CardanoMode ()
    }

-- | Events as generated by the Wallet. They will be translated into
-- UI-compatible events in the 'Glue' module. They must be independent from the
-- UI and capture /what the backend can generate/, not what the frontend can
-- handle.
data WalletEvent =
  WalletUserSecretSetEvent UserSecret
