<<: !include "../../hpack/module.yaml"

name: ariadne-cardano

library:
  <<: *lib-common
  default-extensions:
    - DerivingStrategies
  dependencies:
    - Cabal
    - Earley
    - MissingH
    - QuickCheck
    - acid-state
    - aeson
    - ansi-wl-pprint
    - ariadne-core
    - async
    - beam-core
    - beam-migrate
    - beam-sqlite
    - bytestring
    - cardano-crypto
    - cardano-sl
    - cardano-sl-binary
    - cardano-sl-client
    - cardano-sl-chain
    - cardano-sl-core
    - cardano-sl-crypto
    - cardano-sl-db
    - cardano-sl-infra
    - cardano-sl-networking
    - cardano-sl-util
    - componentm
    - conduit
    - constraints
    - containers
    - contravariant
    - cryptonite
    - data-default
    - dhall
    - directory
    - exceptions
    - file-embed
    - filelock
    - filepath
    - fmt
    - formatting
    - http-client
    - http-client-tls
    - insert-ordered-containers
    - ixset-typed
    - knit
    - lens
    - loot-crypto
    - megaparsec
    - memory
    - monad-control
    - mtl
    - mwc-random
    - named
    - natural-transformation
    - ntype
    - optparse-applicative
    - process
    - resourcet
    - retry
    - safe
    - safe-exceptions
    - safecopy
    - scientific
    - serokell-util
    - spoon
    - sqlite-simple
    - sqlite-simple-errors
    - stm
    - template-haskell
    - text
    - time
    - time-units
    - transformers
    - transformers-base
    - unliftio
    - unliftio-core
    - unordered-containers
    - vector
    - vinyl
    - yaml

tests:
  ariadne-cardano-test:
    <<: *test-common
    dependencies:
      - QuickCheck
      - ariadne-cardano
      - ariadne-core
      - base16-bytestring
      - bytestring
      - canonical-json
      - cardano-crypto
      - cardano-sl
      - cardano-sl-core
      - cardano-sl-core-test
      - cardano-sl-crypto
      - cardano-sl-infra
      - data-default
      - hspec
      - knit
      - lens
      - memory
      - ntype
      - optparse-applicative
      - scientific
      - serokell-util
      - spoon
      - text
      - time-units
      - yaml
  backend-test:
    <<: *test-common
    source-dirs: test/backend
    main: WalletUnitTest.hs
    dependencies:
      - acid-state
      - aeson
      - ariadne-cardano
      - bytestring
      - cardano-sl
      - cardano-sl-chain
      - cardano-sl-client
      - cardano-sl-core
      - cardano-sl-core-test
      - cardano-sl-crypto
      - cardano-sl-db
      - cardano-sl-util
      - cardano-sl-util-test
      - componentm
      - conduit
      - constraints
      - containers
      - cryptonite
      - data-default
      - directory
      - filepath
      - formatting
      - hspec
      - lens
      - memory
      - mtl
      - normaldistribution
      - optparse-applicative
      - o-clock
      - QuickCheck
      - quickcheck-instances
      - random
      - reflection
      - safe-exceptions
      - serokell-util
      - tabl
      - temporary
      - text
      - time
      - unliftio-core
      - unordered-containers
      - vector
    ghc-options:
      # Wallet tests trigger this too often to disable it per-module or fix
      - -Wno-incomplete-uni-patterns
