<<: !include "../../hpack/module.yaml"

name: ariadne-common-ui-glue

library:
  <<: *lib-common
  ghc-options:
    - -Wno-unused-top-binds
  dependencies:
    - Earley
    - Hclip
    - ariadne-core
    - ariadne-cardano
    - ariadne-common-ui-face
    - componentm
    - concurrent-extra
    - containers
    - directory
    - double-conversion
    - formatting
    - ntype
    # UI is independent of Knit, but provides Knit command bindings
    - knit
    - lens
    - loc
    - named
    - serokell-util
    - streams
    - text
    - ansi-wl-pprint
    - text-zipper
    - transformers
    - vector
    - vty
    - word-wrap
