<<: !include "../../hpack/module.yaml"

name: ariadne-core

library:
  <<: *lib-common
  dependencies:
    - Earley
    - ansi-wl-pprint
    - async
    - bytestring
    - componentm
    - concurrent-extra
    - containers
    - co-log
    - co-log-core
    - filepath
    - formatting
    - knit
    - lens
    - log-warper
    - megaparsec
    - ntype
    - o-clock
    - sqlite-simple
    - text
    - time
    - transformers
    - unix

tests:
  ariadne-core-test:
    <<: *test-common
    main: Spec.hs
    dependencies:
      - ariadne-core
      - componentm
      - filepath
      - hspec
      - temporary
      - text
