<<: !include "../../hpack/module.yaml"

name: ariadne-core

library:
  <<: *lib-common
  dependencies:
    - Earley
    - ansi-wl-pprint
    - async
    - componentm
    - concurrent-extra
    - containers
    - formatting
    - knit
    - lens
    - log-warper
    - megaparsec
    - ntype
    - o-clock
    - sqlite-simple
    - text
    - time
    - transformers
    - unix
